### ISSUE TITLE
Repo Feedback

### ISSUE THREAD

**Issue by patrickwhardy** [Jacksonmcguire/intention-timer#27]
Hey all. I just went thru the repo and tried to note stuff I might look at. I couldn't comment per line like in a PR, but here are the files and the line # corresponding with the comment. Nice Work!

Main.js
28: could wrap all query selectors + event listeners in some kind of “init()” function that gets called on window.load. This way you know all DOM elements are ready before you start manipulating them.
36: what do you do on submit? Best to have all your submit logic here so it’s not defined in multiple spots. This line makes me think the submit button is just disabled when I realize you are handling it elsewhere.
50: Doesn’t look like you need string interpolation here. Could be just timerText.innerText= inputActivity.value
69: have you seen “foreach” yet? This could be a good place to use that iterator instead of a regular for loop. I generally prefer it as it’s a bit cleaner syntax b/c you don’t have to select elements by index.
169: Nice solution for creating markup dynamically here.
242: this is a bit dangerous: there is a pattern to the how the local storage item’s key is named that’s not explicitly defined somewhere. People sometimes refer to that as a “magic string”. It can be helpful for future developers if you have something like this.storagePrefix = storage; and then here you can say localStorage.getItem(`${this.storagePrefix}${i}); also, there’s a mix of string interpolation + string concatenation throughout that you could make more consistent.
activity.js looks great. Good job isolating concerns here. One further step you could think about is how to remove any DOM manipulation from this file i.e. the timer text. That would improve how it’s strictly a “model” and not responsible for updating the interface.
HTML looks great - great job with the consistent classes and semantic markup. One thing I would look into is having 1 js import. Try importing Activity.js into main.js, so that you only import main.js in your markup. This helps make your js more clear when you say new Activity() etc as you can see where that class comes from.
CSS: appreciate the comments and sections here. Typo on line 189. Looks like you’ve cleaned up any repeating rules which is good. Maybe just give it a once over to make sure there aren’t any rules that don’t work.

**Comment by elizhahn** [comment]
Thanks Patrick for taking the time to look through our files. Super appreciate the feedback. 

We are working through your suggestions now!
